"""add crop advances table

Revision ID: 40c674fbc3db
Revises: 56f96522a925
Create Date: 2026-08-03 16:12:12.694425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c674fbc3db'
down_revision: Union[str, Sequence[str], None] = '56f96522a925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('advance_type', sa.Enum('unconditional_credit', 'crop_consignment', name='advancetype'), nullable=False),
    sa.Column('advance_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('crop_type', sa.String(), nullable=True),
    sa.Column('expected_qty', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('pricing_mode', sa.Enum('fixed', 'market_minus_commission', name='pricingmode'), nullable=True),
    sa.Column('status', sa.Enum('offered', 'accepted', 'disbursed', 'repaying', 'settled', 'extended', name='advancestatus'), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_advances_broker_id'), 'crop_advances', ['broker_id'], unique=False)
    op.create_index(op.f('ix_crop_advances_farmer_id'), 'crop_advances', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_crop_advances_id'), 'crop_advances', ['id'], unique=False)
    op.create_table('record_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('input_credit', 'credit_repayment', 'crop_advance', 'advance_repayment', 'broker_commission', 'net_payment', name='recordentrytype'), nullable=False),
    sa.Column('direction', sa.Enum('debit', 'credit', name='recorddirection'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_entries_farmer_id'), 'record_entries', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_record_entries_id'), 'record_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_entries_id'), table_name='record_entries')
    op.drop_index(op.f('ix_record_entries_farmer_id'), table_name='record_entries')
    op.drop_table('record_entries')
    op.drop_index(op.f('ix_crop_advances_id'), table_name='crop_advances')
    op.drop_index(op.f('ix_crop_advances_farmer_id'), table_name='crop_advances')
    op.drop_index(op.f('ix_crop_advances_broker_id'), table_name='crop_advances')
    op.drop_table('crop_advances')
    # ### end Alembic commands ###
