"""add contract demand, allocation, and delivery tables

Revision ID: 548723181ca9
Revises: 853985c63ff3
Create Date: 2026-08-03 19:53:06.315692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548723181ca9'
down_revision: Union[str, Sequence[str], None] = '853985c63ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE recordentrytype ADD VALUE IF NOT EXISTS 'contract_payment'")
    op.create_table('contract_demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('quantity_needed', sa.Float(), nullable=False),
    sa.Column('price_offered', sa.Float(), nullable=False),
    sa.Column('quality_specs', sa.String(), nullable=True),
    sa.Column('delivery_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'fulfilled', 'cancelled', name='contractdemandstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_demands_factory_id'), 'contract_demands', ['factory_id'], unique=False)
    op.create_index(op.f('ix_contract_demands_id'), 'contract_demands', ['id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('contract', 'listing', name='sourcetype'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('delivered_qty', sa.Float(), nullable=False),
    sa.Column('quality_grade', sa.Enum('A', 'B', 'C', name='qualitygrade'), nullable=False),
    sa.Column('price_adjustment_percent', sa.Float(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_table('contract_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('requested_qty', sa.Float(), nullable=False),
    sa.Column('allocated_qty', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'delivered', name='allocationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['contract_demands.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_allocations_demand_id'), 'contract_allocations', ['demand_id'], unique=False)
    op.create_index(op.f('ix_contract_allocations_farmer_id'), 'contract_allocations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_contract_allocations_id'), 'contract_allocations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_contract_allocations_id'), table_name='contract_allocations')
    op.drop_index(op.f('ix_contract_allocations_farmer_id'), table_name='contract_allocations')
    op.drop_index(op.f('ix_contract_allocations_demand_id'), table_name='contract_allocations')
    op.drop_table('contract_allocations')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_contract_demands_id'), table_name='contract_demands')
    op.drop_index(op.f('ix_contract_demands_factory_id'), table_name='contract_demands')
    op.drop_table('contract_demands')
    # ### end Alembic commands ###
    
    # NOTE: Postgres has no ALTER TYPE ... DROP VALUE. Removing 'contract_payment'
    # from recordentrytype would require rebuilding the type entirely — not attempted here.
    
    # op.drop_table() does NOT drop the Postgres enum types backing Enum columns —
    # Alembic only reflects the bare table name on drop, not its column/type
    # definitions. Without these explicit drops, re-running upgrade() after a
    # downgrade fails with "type already exists" (exactly what just happened).
    op.execute("DROP TYPE IF EXISTS contractdemandstatus")
    op.execute("DROP TYPE IF EXISTS allocationstatus")
    op.execute("DROP TYPE IF EXISTS qualitygrade")
    op.execute("DROP TYPE IF EXISTS sourcetype")
        