"""add input products table

Revision ID: 56f96522a925
Revises: 36f1819e84e5
Create Date: 2026-08-03 08:38:37.534648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f96522a925'
down_revision: Union[str, Sequence[str], None] = '36f1819e84e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopkeeper_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('seed', 'fertilizer', 'pesticide', 'equipment', 'other', name='inputcategory'), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('stock_qty', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shopkeeper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_products_id'), 'input_products', ['id'], unique=False)
    op.create_index(op.f('ix_input_products_shopkeeper_id'), 'input_products', ['shopkeeper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_input_products_shopkeeper_id'), table_name='input_products')
    op.drop_index(op.f('ix_input_products_id'), table_name='input_products')
    op.drop_table('input_products')
    # ### end Alembic commands ###
