"""add crop listings and consumer orders

Revision ID: 9b767a7c1e68
Revises: 548723181ca9
Create Date: 2026-08-04 04:49:44.482967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b767a7c1e68'
down_revision: Union[str, Sequence[str], None] = '548723181ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute("ALTER TYPE recordentrytype ADD VALUE IF NOT EXISTS 'crop_sale'")
    
    op.create_table('consumer_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.Enum('cash_on_delivery', name='consumerpaymentmode'), nullable=False),
    sa.Column('status', sa.Enum('placed', 'delivered', 'cancelled', name='consumerorderstatus'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consumer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_orders_consumer_id'), 'consumer_orders', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_consumer_orders_id'), 'consumer_orders', ['id'], unique=False)
    op.create_table('crop_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('listed_by_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('quality_grade', sa.Enum('A', 'B', 'C', name='listingqualitygrade'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('retail_available', sa.Boolean(), nullable=False),
    sa.Column('retail_unit_size', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'sold_out', 'closed', name='listingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_listings_farmer_id'), 'crop_listings', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_crop_listings_id'), 'crop_listings', ['id'], unique=False)
    op.create_table('consumer_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['crop_listings.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['consumer_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_order_items_id'), 'consumer_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_consumer_order_items_listing_id'), 'consumer_order_items', ['listing_id'], unique=False)
    op.create_index(op.f('ix_consumer_order_items_order_id'), 'consumer_order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumer_order_items_order_id'), table_name='consumer_order_items')
    op.drop_index(op.f('ix_consumer_order_items_listing_id'), table_name='consumer_order_items')
    op.drop_index(op.f('ix_consumer_order_items_id'), table_name='consumer_order_items')
    op.drop_table('consumer_order_items')
    op.drop_index(op.f('ix_crop_listings_id'), table_name='crop_listings')
    op.drop_index(op.f('ix_crop_listings_farmer_id'), table_name='crop_listings')
    op.drop_table('crop_listings')
    op.drop_index(op.f('ix_consumer_orders_id'), table_name='consumer_orders')
    op.drop_index(op.f('ix_consumer_orders_consumer_id'), table_name='consumer_orders')
    op.drop_table('consumer_orders')
    # ### end Alembic commands ###
    
    op.execute("DROP TYPE IF EXISTS listingqualitygrade")
    op.execute("DROP TYPE IF EXISTS liststatus")
    op.execute("DROP TYPE IF EXISTS consumerpaymentmode")
    op.execute("DROP TYPE IF EXISTS consumerorderstatus")
