"""add input orders and input order items tables

Revision ID: ea917cfa2b8f
Revises: c0d6183e2120
Create Date: 2026-08-04 07:13:12.809490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea917cfa2b8f'
down_revision: Union[str, Sequence[str], None] = 'c0d6183e2120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('shopkeeper_id', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.Enum('cash', 'credit', name='inputpaymentmode'), nullable=False),
    sa.Column('credit_markup_percent', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('placed', 'settled', name='inputorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shopkeeper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_orders_farmer_id'), 'input_orders', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_input_orders_id'), 'input_orders', ['id'], unique=False)
    op.create_index(op.f('ix_input_orders_shopkeeper_id'), 'input_orders', ['shopkeeper_id'], unique=False)
    op.create_table('input_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['input_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['input_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_order_items_id'), 'input_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_input_order_items_order_id'), 'input_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_input_order_items_product_id'), 'input_order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_input_order_items_product_id'), table_name='input_order_items')
    op.drop_index(op.f('ix_input_order_items_order_id'), table_name='input_order_items')
    op.drop_index(op.f('ix_input_order_items_id'), table_name='input_order_items')
    op.drop_table('input_order_items')
    op.drop_index(op.f('ix_input_orders_shopkeeper_id'), table_name='input_orders')
    op.drop_index(op.f('ix_input_orders_id'), table_name='input_orders')
    op.drop_index(op.f('ix_input_orders_farmer_id'), table_name='input_orders')
    op.drop_table('input_orders')
    # ### end Alembic commands ###
